"""Add foreign keys of entities to project

Revision ID: 49925c3678fa
Revises: f97c34b34611
Create Date: 2019-01-19 10:11:42.122558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49925c3678fa'
down_revision = 'f97c34b34611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'deliverables', 'projects', ['project_id'], ['project_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'issues', 'projects', ['project_id'], ['project_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_constraint(None, 'deliverables', type_='foreignkey')
    # ### end Alembic commands ###
