"""Init db

Revision ID: 88ed88c89cb3
Revises: 
Create Date: 2019-01-13 21:48:04.041794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ed88c89cb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliverables',
    sa.Column('object_id', sa.String(length=15), nullable=False),
    sa.Column('project_id', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=9), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('date_opened', sa.DateTime(), nullable=False),
    sa.Column('date_closed', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_index(op.f('ix_deliverables_project_id'), 'deliverables', ['project_id'], unique=False)
    op.create_table('field_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.String(length=15), nullable=False),
    sa.Column('uri', sa.String(length=2048), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'uri')
    )
    op.create_index(op.f('ix_field_files_parent_id'), 'field_files', ['parent_id'], unique=False)
    op.create_index(op.f('ix_field_files_uri'), 'field_files', ['uri'], unique=False)
    op.create_table('field_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.String(length=15), nullable=False),
    sa.Column('uri', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=126), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'uri')
    )
    op.create_index(op.f('ix_field_links_parent_id'), 'field_links', ['parent_id'], unique=False)
    op.create_table('field_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.String(length=15), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'tag')
    )
    op.create_index(op.f('ix_field_tags_parent_id'), 'field_tags', ['parent_id'], unique=False)
    op.create_index(op.f('ix_field_tags_tag'), 'field_tags', ['tag'], unique=False)
    op.create_table('field_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.String(length=15), nullable=False),
    sa.Column('task', sa.String(length=1024), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'task')
    )
    op.create_index(op.f('ix_field_tasks_parent_id'), 'field_tasks', ['parent_id'], unique=False)
    op.create_table('ids_counter',
    sa.Column('project_id', sa.String(length=15), nullable=False),
    sa.Column('next_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('issues',
    sa.Column('object_id', sa.String(length=15), nullable=False),
    sa.Column('project_id', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('external_type', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=11), nullable=False),
    sa.Column('priority', sa.String(length=11), nullable=False),
    sa.Column('type', sa.String(length=11), nullable=False),
    sa.Column('date_opened', sa.DateTime(), nullable=False),
    sa.Column('date_closed', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('hour_rate_amount', sa.DECIMAL(), nullable=True),
    sa.Column('hour_rate_currency', sa.String(length=3), nullable=True),
    sa.Column('estimated_duration', sa.DECIMAL(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_index(op.f('ix_issues_project_id'), 'issues', ['project_id'], unique=False)
    op.create_table('objects_tracker',
    sa.Column('id', sa.String(length=15), nullable=False),
    sa.Column('project_id', sa.String(length=5), nullable=False),
    sa.Column('type', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objects_tracker_project_id'), 'objects_tracker', ['project_id'], unique=False)
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=9), nullable=False),
    sa.Column('date_opened', sa.DateTime(), nullable=False),
    sa.Column('date_closed', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('hour_rate_amount', sa.DECIMAL(), nullable=True),
    sa.Column('hour_rate_currency', sa.String(length=3), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('limitations_and_restrictions', sa.String(), nullable=False),
    sa.Column('goals_and_metrics', sa.String(), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('secondary_color', sa.String(length=7), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.LargeBinary(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('entity_links',
    sa.Column('object_id', sa.String(length=15), nullable=False),
    sa.Column('other_object_id', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects_tracker.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['other_object_id'], ['objects_tracker.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('object_id', 'other_object_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_links')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_index(op.f('ix_objects_tracker_project_id'), table_name='objects_tracker')
    op.drop_table('objects_tracker')
    op.drop_index(op.f('ix_issues_project_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_table('ids_counter')
    op.drop_index(op.f('ix_field_tasks_parent_id'), table_name='field_tasks')
    op.drop_table('field_tasks')
    op.drop_index(op.f('ix_field_tags_tag'), table_name='field_tags')
    op.drop_index(op.f('ix_field_tags_parent_id'), table_name='field_tags')
    op.drop_table('field_tags')
    op.drop_index(op.f('ix_field_links_parent_id'), table_name='field_links')
    op.drop_table('field_links')
    op.drop_index(op.f('ix_field_files_uri'), table_name='field_files')
    op.drop_index(op.f('ix_field_files_parent_id'), table_name='field_files')
    op.drop_table('field_files')
    op.drop_index(op.f('ix_deliverables_project_id'), table_name='deliverables')
    op.drop_table('deliverables')
    # ### end Alembic commands ###
