"""Add costs tables

Revision ID: f97c34b34611
Revises: 88ed88c89cb3
Create Date: 2019-01-15 20:34:42.411819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f97c34b34611'
down_revision = '88ed88c89cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenditures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.String(length=15), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('date_opened', sa.DateTime(), nullable=False),
    sa.Column('date_closed', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=9), nullable=True),
    sa.Column('type', sa.String(length=9), nullable=True),
    sa.Column('cost_amount', sa.DECIMAL(), nullable=True),
    sa.Column('cost_currency', sa.String(length=3), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenditures_parent_id'), 'expenditures', ['parent_id'], unique=False)
    op.create_table('timesheets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.String(length=15), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('duration', sa.DECIMAL(), nullable=False),
    sa.Column('date_opened', sa.DateTime(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timesheets_parent_id'), 'timesheets', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timesheets_parent_id'), table_name='timesheets')
    op.drop_table('timesheets')
    op.drop_index(op.f('ix_expenditures_parent_id'), table_name='expenditures')
    op.drop_table('expenditures')
    # ### end Alembic commands ###
