version: '3'

services:
  work-tracking:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: tm/work-tracking
    volumes:
      - ./backend/src/wt:/app/wt
      - ./backend/tests:/app/tests
    environment:
      - PYTHONPATH=$PYTHONPATH:/app:/app/debug_egg/debug.egg
    ports:
      - 8080:8080
    command: [
      "python3", "/app/wt/app.py"
    ]
