"""Init db

Revision ID: 82a91a771355
Revises: 
Create Date: 2019-01-10 20:38:14.063415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a91a771355'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliverables',
    sa.Column('object_id', sa.String(length=15), nullable=False),
    sa.Column('project_id', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=9), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('date_opened', sa.DateTime(), nullable=False),
    sa.Column('date_closed', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_index(op.f('ix_deliverables_project_id'), 'deliverables', ['project_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.String(length=15), nullable=False),
    sa.Column('uri', sa.String(length=64), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'uri')
    )
    op.create_index(op.f('ix_files_uri'), 'files', ['uri'], unique=False)
    op.create_table('ids_counter',
    sa.Column('project_id', sa.String(length=15), nullable=False),
    sa.Column('next_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('objects_tracker',
    sa.Column('id', sa.String(length=15), nullable=False),
    sa.Column('project_id', sa.String(length=5), nullable=False),
    sa.Column('type', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objects_tracker_project_id'), 'objects_tracker', ['project_id'], unique=False)
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=9), nullable=False),
    sa.Column('date_opened', sa.DateTime(), nullable=False),
    sa.Column('date_closed', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('hour_rate_amount', sa.DECIMAL(), nullable=True),
    sa.Column('hour_rate_currency', sa.String(length=3), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('limitations_and_restrictions', sa.String(), nullable=False),
    sa.Column('goals_and_metrics', sa.String(), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('secondary_color', sa.String(length=7), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.LargeBinary(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_index(op.f('ix_objects_tracker_project_id'), table_name='objects_tracker')
    op.drop_table('objects_tracker')
    op.drop_table('ids_counter')
    op.drop_index(op.f('ix_files_uri'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_deliverables_project_id'), table_name='deliverables')
    op.drop_table('deliverables')
    # ### end Alembic commands ###
