"""Init db for projects

Revision ID: d86622fec7d1
Revises: 
Create Date: 2019-01-08 11:00:02.186757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86622fec7d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.String(length=15), nullable=True),
    sa.Column('uri', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'uri')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=9), nullable=False),
    sa.Column('date_opened', sa.DateTime(), nullable=False),
    sa.Column('date_closed', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('hour_rate_amount', sa.DECIMAL(), nullable=True),
    sa.Column('hour_rate_currency', sa.String(length=3), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('limitations_and_restrictions', sa.String(), nullable=False),
    sa.Column('goals_and_metrics', sa.String(), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('secondary_color', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.LargeBinary(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('files')
    # ### end Alembic commands ###
