"""Add issues related tables

Revision ID: e63bf40ec77e
Revises: 82a91a771355
Create Date: 2019-01-13 15:49:44.618292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63bf40ec77e'
down_revision = '82a91a771355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('object_id', sa.String(length=15), nullable=False),
    sa.Column('project_id', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('external_type', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=11), nullable=False),
    sa.Column('priority', sa.String(length=11), nullable=False),
    sa.Column('type', sa.String(length=11), nullable=False),
    sa.Column('date_opened', sa.DateTime(), nullable=False),
    sa.Column('date_closed', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('hour_rate_amount', sa.DECIMAL(), nullable=True),
    sa.Column('hour_rate_currency', sa.String(length=3), nullable=True),
    sa.Column('estimated_duration', sa.DECIMAL(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_index(op.f('ix_issues_project_id'), 'issues', ['project_id'], unique=False)
    op.create_table('links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.String(length=15), nullable=False),
    sa.Column('uri', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=126), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'uri')
    )
    op.create_index(op.f('ix_links_parent_id'), 'links', ['parent_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.String(length=15), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'tag')
    )
    op.create_index(op.f('ix_tags_parent_id'), 'tags', ['parent_id'], unique=False)
    op.create_index(op.f('ix_tags_tag'), 'tags', ['tag'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.String(length=15), nullable=False),
    sa.Column('task', sa.String(length=1024), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'task')
    )
    op.create_index(op.f('ix_tasks_parent_id'), 'tasks', ['parent_id'], unique=False)
    op.create_index(op.f('ix_files_parent_id'), 'files', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_parent_id'), table_name='files')
    op.drop_index(op.f('ix_tasks_parent_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_tags_tag'), table_name='tags')
    op.drop_index(op.f('ix_tags_parent_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_links_parent_id'), table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_issues_project_id'), table_name='issues')
    op.drop_table('issues')
    # ### end Alembic commands ###
